# Generated by Django 5.0.7 on 2024-07-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=25)),
                ("last_name", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=25)),
                ("phone", models.CharField(max_length=25)),
                ("address", models.CharField(max_length=25)),
                ("zip", models.CharField(max_length=5)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
