# Generated by Django 5.0.7 on 2024-08-01 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutageReport",
            fields=[
                ("report_id", models.AutoField(primary_key=True, serialize=False)),
                ("report_date", models.DateTimeField(auto_now_add=True)),
                ("location", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=500)),
                ("status", models.CharField(max_length=50)),
                ("planned", models.BooleanField(default=False)),
                ("estimates_restoration_time", models.DateTimeField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
