# Generated by Django 5.0.7 on 2024-08-02 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("outages", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="outagereport",
            old_name="estimates_restoration_time",
            new_name="estimated_restoration_time",
        ),
    ]
