# Generated by Django 5.0.7 on 2024-08-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "outages",
            "0002_rename_estimates_restoration_time_outagereport_estimated_restoration_time",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="outagereport",
            name="status",
            field=models.CharField(
                choices=[
                    ("reported", "Reported"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                ],
                default="reported",
                max_length=50,
            ),
        ),
    ]
