# Generated by Django 5.0.7 on 2024-08-12 02:21

from django.db import migrations, models

def SetDefaultZipCode(apps, schema_editor):
    OutageReport = apps.get_model('outages','OutageReport')
    OutageReport.objects.filter(zip_code__isnull = True).update(zip_code='00000')
class Migration(migrations.Migration):

    dependencies = [
        ('outages', '0003_alter_outagereport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='outagereport',
            name='zip_code',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.RunPython(SetDefaultZipCode)
    ]
