# Generated by Django 5.0.7 on 2024-08-12 02:44

from django.db import migrations

def SetDefaultZipCode(apps, schema_editor):
    OutageReport = apps.get_model('outages','OutageReport')
    OutageReport.objects.filter(zip_code__isnull = True).update(zip_code='00000')

class Migration(migrations.Migration):

    dependencies = [
        ('outages', '0004_outagereport_zip_code'),
    ]

    operations = [
        migrations.RunPython(SetDefaultZipCode),
    ]
